name: Unit Tests
on:
  push:
    branches:
      - main

jobs:
  test:
    permissions:
      contents: write
      pull-requests: write
    uses: OMICRONEnergyOSS/oscd-gh-workflows/.github/workflows/unit-tests.yml@main
    # if the plugin has VRT's, then use this workflow instead:
    # uses: OMICRONEnergyOSS/oscd-gh-workflows/.github/workflows/unit-and-vrt-tests.yml@main
